### ISSUE TITLE
Google & Facebook logins not working in mobile browsers

### ISSUE THREAD

**Issue by srikanth240369** [laravel/socialite#293]
Google & Facebook logins not working in mobile browsers. It is showing 400 error redirect_uri_mismatching(Even if it is correct)
![352d6770-06fc-4bad-8fdc-0f5a08293f13](https://user-images.githubusercontent.com/12655260/47922224-8deb9c80-dedc-11e8-942a-b08ca1da3a7c.jpg)

**Comment by driesvints** [comment]
I suspect that this isn't a Socialite bug but rather an incorrect configuration somewhere. Can you please try one of the following support channels and report back if you have confirmed that the bug is indeed coming from Socialite?

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by tereaksmey123** [comment]
@srikanth240369 i meet this problem before maybe u set Driver (callback url )in server.php difference from the callbacl url u config in Facebook Dev / Google console redirect url check that.

**Comment by HoangQuan** [comment]
I got same problem when I try to login by Facebook on mobile browser.
it's worked fine on PC and on mobile too when I choose chrome as default browser

![image](https://user-images.githubusercontent.com/3013122/63354354-81aece00-c38e-11e9-841d-87431044b9c2.png)
any help? plz
Thanks

**Comment by HoangQuan** [comment]
OMG. finally, I have fixed this happen.

This happen because open facebook app to get response from Facebook API make we lost some cookie. it's become stateless.
Then I just use the option that `socialite` are already made to avoid `stateless` request.
```
$user = Socialite::driver($provider)->stateless()->user();
```
It's worked to me.

**Comment by minhhieu08** [comment]
Found it on https://laravel.com/docs/5.8/socialite#stateless-authentication. Anyway thank @HoangQuan 😎😎

**Comment by twf-nikhila** [comment]
In mobile for Facebook or Google auth, it doesn't redirects to installed fb/Google app, instead it takes to browser.

How to redirect to the respective apps?
