### ISSUE TITLE
[v3] Google+ APIs being shutdown

### ISSUE THREAD

**Issue by fhriz** [laravel/socialite#317]
Hi,

I'm still using laravel 5.4 for php version reason. But, I got an email which saying that Google+ APIs being shutdown. But, unfortunately the changes are made for v4. Could you help me how I can use the changes which made in #283 for v3 ?

Thanks

**Comment by dionmes** [comment]
Same here, still on 5.5 because of the LTS. I also got the email from Google that 'plus.people.get' method is being called and its deprecated.

**Comment by driesvints** [comment]
Pr got merged. You can pull in `3.0.x-dev` if you like.

**Comment by driesvints** [comment]
@kennith since we don't support 3.0 anymore probably not

**Comment by kidager** [comment]
> @kennith since we don't support 3.0 anymore probably not

@driesvints I don't understand, if Laravel 5.5 is LTS (and is still supported) and it uses Socialite `^3.0`, shouldn't it still be supported too ? If not what's the point of it being an LTS version if used **laravel** libraries aren't.

Following that logic, someone creating a fresh laravel project using version 5.5 (I'm totally against, but it is still supported) will not be able to install a working version of Socialite, v4 requires Laravel 5.7, and v3 isn't supported anymore!

**Comment by driesvints** [comment]
@kidager LTS only applies for the framework and not the other libraries.

**Comment by GrahamCampbell** [comment]
> don't you think this is why people think PHP for the enterprise is a joke?

PHP has one of the best package ecosystems of any language actually, so I disagree.

**Comment by kidager** [comment]
> PHP has one of the best package ecosystems of any language actually, so I disagree.

I totally agree with you there. But this is going to be a critical bug for every Socialite user managing a Laravel installation of v5.6 or less (Keeping always in mind that 5.5 is still supported and that **laravel/socialite** is part of laravel, not included by default, but still a part of the laravel ecosystem)

So seeing that a simple fix won't be applied for a library we're using in prod does not make me want to use it anymore! Even with the newer versions.

And we all agree here that the fix is not something complicated, it's enough to replace the class in the container. But that's not the point, the point is the PR is accepted but won't be applied which ignores totally the users base need. No one will reference a "dev" version in their prod environment.

**Comment by driesvints** [comment]
@kidager we merged the pr and you can require it with Composer by requiring `3.0.x-dev` like I said above.

**Comment by kidager** [comment]
> @kidager we merged the pr and you can require it with Composer by requiring `3.0.x-dev` like I said above.

> No one will reference a "dev" version in their prod environment.

**Comment by driesvints** [comment]
Honestly, if all you're going to do is complain it's best that we just lock this.
