### ISSUE TITLE
Retrieve original avatar for Google

### ISSUE THREAD

**Issue by mkuzmych** [laravel/socialite#357]
- Socialite Version: v3.2.0
- Laravel Version: v5.7.22
- PHP Version: PHP 7.1.6
- Database Driver & Version: mysql

### Description:
Wrong avatar original for Google API:

image['url'] => https://lh5.googleusercontent.com/-S9cRpbIvumo/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfuJ7kOYuvkSMSwjgO2hVEX3wy0qA/s50-mo/photo.jpg
avatar_original => https://lh5.googleusercontent.com/-S9cRpbIvumo/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfuJ7kOYuvkSMSwjgO2hVEX3wy0qA/s50-mo/photo.jpg

But original size is https://lh5.googleusercontent.com/-S9cRpbIvumo/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rfuJ7kOYuvkSMSwjgO2hVEX3wy0qA/photo.jpg

**Comment by driesvints** [comment]
The current "userinfo" calls returns the basic OpenID connect fields which you can see here: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

I'm not sure if another claim is supported to retrieve the original avatar. At the moment I'm going to flag this as a feature request rather than a bug. If you can figure it out how to retrieve the original avatar as well from the userinfo call then feel free to send in a PR.

**Comment by theodh** [comment]
@uapixart a lot of fields are now deprecated. Also didn't find this in the [scope api](https://developers.google.com/identity/protocols/googlescopes).

Extra feature's for resizing in the picture url:
 https://developers.google.com/people/image-sizing

Example original: 
![](https://lh3.googleusercontent.com/a-/AAuE7mBtOEJdcqULrU6YDspwsKjbN0-_cIvogg64xTkvsQ)
https://lh3.googleusercontent.com/a-/AAuE7mBtOEJdcqULrU6YDspwsKjbN0-_cIvogg64xTkvsQ


Size change with parameter =s100-c:
![](https://lh3.googleusercontent.com/a-/AAuE7mBtOEJdcqULrU6YDspwsKjbN0-_cIvogg64xTkvsQ=s100-c)
https://lh3.googleusercontent.com/a-/AAuE7mBtOEJdcqULrU6YDspwsKjbN0-_cIvogg64xTkvsQ=s100-c

Perhaps we could close this issue?

**Comment by driesvints** [comment]
Seems like what @theodh is the correct solution to resizing images. 

@theodh I think just letting people do this in userland is fine.
