### ISSUE TITLE
[linkedIn] vanityName is missing in the linkedIn integration

### ISSUE THREAD

**Issue by vinceinfluo** [laravel/socialite#380]
> The vanityName from Basic Profile Fields is used to represent the public profile URL in the follow format: www.linkedin.com/in/{vanityName}.

This is missing in the current integration, would be nice to see this added.

**Comment by driesvints** [comment]
I remember that when I refactored the linkedin integration that I needed to explicitly use the `r_liteprofile` scope instead of the `r_basicprofile` scope but I can't remember the reason why. The vanity name is included in the `r_basicprofile` but I'm unsure what the consequences would be of using that instead. I think at the worst it'll break people's apps because the integration will suddenly request more fields than the user has access to and prevent them from logging in.

Maybe it's better that we tackle https://github.com/laravel/socialite/issues/368 instead so you can explicitly set other scopes in your app. This would prevent the above problem. In any case the current scopes are enough for a basic login (which is the main purpose of socialite).
