### ISSUE TITLE
Driver parameters can't be overridden during token validation phase

### ISSUE THREAD

**Issue by lakerobin** [laravel/socialite#382]
- Socialite Version: 4.1.3
- Laravel Version: 5.8.29
- PHP Version: 7.3.7
- Database Driver & Version:

### Description:
Overriding driver parameters using `with` method does not work during token verification phase.

### Steps To Reproduce:
I am not setting redirect_uri in the config, as I plan to use different uri's for different type of users.

`//Redirecting to google login - Works`
Socialite::driver('google')->with(['redirect_uri' => '/my/redirect/uri'])->redirect(); 

`//Callback from google login - Does not work`
Socialite::driver('google')->with(['redirect_uri' => '/my/redirect/uri'])->user();

#### Exception raised:
```
Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `400 Bad  Request` response:
{
  "error": "invalid_request",
  "error_description": "Missing parameter: redirect_uri"
}
```

### Possible Cause
`getCodeFields()` method uses array_merge of provided fields with the parameters set using `with` method. However, `getTokenFields()` method doesn't do so.

### Workaround
For the `redirect_uri` parameter, we have a workaround of using `redirectUrl` method, however, other parameters like `client_id` can't be overridden.

**Comment by driesvints** [comment]
Heya @lakerobin. Can you maybe show exactly which could would need to be update for this? You're always free to send in a PR for this if you want. Make sure to add a test which covers the scenario.

**Comment by mycarrysun** [comment]
I need this too! Staff members have a different URL for their login screen so I am using 2 different redirect uri bases

**Comment by ihtisham467** [comment]
Hi @lakerobin Can you provide me the code.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by adwiv** [comment]
Here are the offending code mentioned by @lakerobin in the `AbstractProvider` class.

When we call `with([])` method, the passed array is stored as `$parameters` field.

https://github.com/laravel/socialite/blob/65f474ac5ed5b24d1dfd5daca0fae7b383530f78/src/Two/AbstractProvider.php#L434-L436

`getCodeFields` method is called to get all the fields for making a request to the provider. In this method, an array merge is used with the `$parameters` fields, allowing the values from config to be overridden using the array passed to `with()` method.

https://github.com/laravel/socialite/blob/65f474ac5ed5b24d1dfd5daca0fae7b383530f78/src/Two/AbstractProvider.php#L176-L190

`getTokenFields` method is called during the token verification phase. In this method, there is no merge with `$parameters`, resulting on the config file values being sent to the server.

https://github.com/laravel/socialite/blob/65f474ac5ed5b24d1dfd5daca0fae7b383530f78/src/Two/AbstractProvider.php#L277-L285

The fix is to make `getTokenFields` merge the `$parameters` values. For safety, we can limit the parameters being merged to only the relevant keys.

```php
protected function getTokenFields($code) 
{ 
     return array_merge([ 
         'client_id' => $this->clientId, 
         'client_secret' => $this->clientSecret, 
         'code' => $code, 
         'redirect_uri' => $this->redirectUrl, 
     ], Arr::only($this->parameters, ['client_id', 'client_secret', 'redirect_uri'])); 
} 
```
