### ISSUE TITLE
Apple ID sign-in api or web

### ISSUE THREAD

**Issue by degeta10** [laravel/socialite#451]
Is it possible to integrate apple sign-in using api or web. Currently there exists libraries for apple sign-in but it supports for web integration only. When will it be possible to integrate Apple sign in using APIs?

**Comment by driesvints** [comment]
We have no intention of supporting more adapters. Please see https://github.com/laravel/socialite/issues/369

**Comment by JorisDebonnet** [comment]
@driesvints, is there any chance of revisiting this discussion in the near future; i.e. to adopt the existing SocialiteProvider solution into this main repo? 

The reason I am asking is because Apple _requires_ any AppStore submissions or even updates to support login with AppleID, if they already support any other providers. This was not yet the case during most of the previous discussion. I believe that due to this requirement by Apple, this provider will keep growing, which could motivate the case to support it in the main repo. (It's probably already used more often than Gitlab, Github or Bitbucket.)

**Comment by driesvints** [comment]
No sorry, we have no plans for this and there's existing solutions already. See https://socialiteproviders.com/Apple/ & https://github.com/m1guelpf/laravel-apple-login
