### ISSUE TITLE
setScopes, scopes and other methods not declared in PHPDoc

### ISSUE THREAD

**Issue by adic3x** [laravel/socialite#647]
### Socialite Version

5.8.0

### Laravel Version

10.*

### PHP Version

8.2.*

### Description

Example from documentation (https://laravel.com/docs/10.x/socialite#access-scopes)
```
use Laravel\Socialite\Facades\Socialite;
 
return Socialite::driver('github')
    ->scopes(['read:user', 'public_repo'])
    ->redirect();
```
```scopes``` highlighted as non-existent method because it not declared in ```socialite\src\Facades\Socialite.php``` https://github.com/laravel/socialite/blob/5.x/src/Facades/Socialite.php (at least in VS Code).

As I understand ```scopes```, ```setScopes```, ```getScopes``` and ```redirectUrl``` must be declared in PHPDoc.

### Steps To Reproduce

Open IDE and paste code.

**Comment by driesvints** [comment]
Please see the contribution docs about docblocks and send in a PR if you want. Thanks

https://laravel.com/docs/10.x/contributions#bug-reports

**Comment by Quadrubo** [comment]
I also have this issue. I get that this is not critical and it's totally fine not to fix it but why close the issue?

When the issue is left open:
1. Someone else who knows how to fix it could stumble upon it and solve it
2. People using socialite will discover the issue instead of trying to debug what's wrong with their setup

if possible please reopen this as it is not solved.
